# Change these first
owner: desdiogo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: App 2Talk
    url: https://app.2talk.com
    icon: https://app.2talk.com/2talk/favicon-32x32.png

  - name: Ci 2 Talk
    url: https://ci-switch.2talk.com/
    icon: https://ci-switch.2talk.com/2talk/favicon-32x32.png
  - name: App Sipcity
    url: https://app.sipcity.com.au/
    icon: https://app.sipcity.com.au/SIPcity/favicon-32x32.png
  - name: Ci Sipcity
    url: https://ci-switch.sipcity.com.au/
    icon: https://ci-switch.sipcity.com.au/SIPcity/favicon-32x32.png

skipDeleteIssues: true

status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: Status

user-agent: desdiogo
